---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "nifi.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "nifi.name" . }}
    chart: {{ template "backendapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "nifi.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: nifi
        image: apache/nifi:1.4.0
        ports:
        - containerPort: {{ .Values.service.nifi.internalPort }}
